"""auto update

Revision ID: 00beb42a0b5f
Revises: 4be4b1ce7d37
Create Date: 2026-02-25 15:33:51.529500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00beb42a0b5f'
down_revision = '4be4b1ce7d37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('borrower_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_seen_dashboard_tour', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('borrower_profile', schema=None) as batch_op:
        batch_op.drop_column('has_seen_dashboard_tour')

    # ### end Alembic commands ###
