"""add subscription column

Revision ID: 08c332fe7527
Revises: ac9d94fc422a
Create Date: 2026-03-25 14:47:17.499582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08c332fe7527'
down_revision = '0002'
branch_labels = None
depends_on = None


def upgrade():
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    user_cols = {c["name"] for c in inspector.get_columns("user")} if inspector.has_table("user") else set()
    with op.batch_alter_table('user', schema=None) as batch_op:
        if "subscription" not in user_cols:
            batch_op.add_column(sa.Column('subscription', sa.String(length=50), nullable=True))

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('subscription')

    # ### end Alembic commands ###