"""Extend AIAuditLog with shared insight fields

Revision ID: 0970fcbaa94a
Revises: c1d19bb33b8d
Create Date: 2025-11-11 09:12:50.579742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0970fcbaa94a'
down_revision = 'c1d19bb33b8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_audit_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('borrower_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('lead_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('context', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('role_view', sa.String(length=50), nullable=True))
        batch_op.create_foreign_key(None, 'lead', ['lead_id'], ['id'])
        batch_op.create_foreign_key(None, 'borrower_profile', ['borrower_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_audit_log', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('role_view')
        batch_op.drop_column('context')
        batch_op.drop_column('lead_id')
        batch_op.drop_column('borrower_id')

    # ### end Alembic commands ###
