"""Add SystemSettings model

Revision ID: 0b9881ace246
Revises: 1de55cbbc53b
Create Date: 2025-11-08 20:33:22.769617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b9881ace246'
down_revision = '1de55cbbc53b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('system_name', sa.String(length=120), nullable=True),
    sa.Column('theme_color', sa.String(length=20), nullable=True),
    sa.Column('ai_mode', sa.String(length=50), nullable=True),
    sa.Column('version', sa.String(length=20), nullable=True),
    sa.Column('maintenance_mode', sa.Boolean(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('system_settings')
    # ### end Alembic commands ###
