"""BorrowerInteraction

Revision ID: 0c35f7e30e0e
Revises: 6c75726b1d62
Create Date: 2025-11-09 21:21:28.587914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c35f7e30e0e'
down_revision = '6c75726b1d62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credit_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('delinquencies', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('total_accounts', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('pulled_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credit_profile', schema=None) as batch_op:
        batch_op.drop_column('pulled_at')
        batch_op.drop_column('total_accounts')
        batch_op.drop_column('delinquencies')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
