"""Add financial metrics to PropertyAnalysis

Revision ID: 1c9076aae2bb
Revises: 40ea79ae5eec
Create Date: 2025-11-08 11:19:08.593964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c9076aae2bb'
down_revision = '40ea79ae5eec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property_analysis', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cash_flow', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('expenses', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('rental_income', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property_analysis', schema=None) as batch_op:
        batch_op.drop_column('rental_income')
        batch_op.drop_column('expenses')
        batch_op.drop_column('cash_flow')

    # ### end Alembic commands ###
