"""auto update

Revision ID: 1de55cbbc53b
Revises: 9679a9358214
Create Date: 2025-11-08 18:59:32.889786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1de55cbbc53b'
down_revision = '9679a9358214'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('partners', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deals', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('volume', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('rating', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('partners', schema=None) as batch_op:
        batch_op.drop_column('created_at')
        batch_op.drop_column('rating')
        batch_op.drop_column('volume')
        batch_op.drop_column('deals')

    # ### end Alembic commands ###
