"""auto update

Revision ID: 1ea77ca3457d
Revises: add_1003_fields
Create Date: 2025-11-15 10:58:11.633185

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1ea77ca3457d'
down_revision = 'add_1003_fields'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('borrower_last_contact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('borrower_id', sa.Integer(), nullable=True),
    sa.Column('last_contact_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['borrower_id'], ['borrower_profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('borrower_message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('borrower_id', sa.Integer(), nullable=False),
    sa.Column('sender_type', sa.String(length=20), nullable=True),
    sa.Column('sender_name', sa.String(length=120), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['borrower_id'], ['borrower_profile.id'], name='fk_msg_borrower'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('soft_credit_report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('borrower_profile_id', sa.Integer(), nullable=True),
    sa.Column('credit_score', sa.Integer(), nullable=True),
    sa.Column('bureau', sa.String(length=50), nullable=True),
    sa.Column('credit_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('monthly_debt_total', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['borrower_profile_id'], ['borrower_profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('communication_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('borrower_id', sa.Integer(), nullable=True),
    sa.Column('loan_id', sa.Integer(), nullable=True),
    sa.Column('channel', sa.String(length=20), nullable=True),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['borrower_id'], ['borrower_profile.id'], ),
    sa.ForeignKeyConstraint(['loan_id'], ['loan_application.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('loan_id', sa.Integer(), nullable=False),
    sa.Column('borrower_id', sa.Integer(), nullable=False),
    sa.Column('document_name', sa.String(length=200), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_agent', sa.String(length=300), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['borrower_id'], ['borrower_profile.id'], ),
    sa.ForeignKeyConstraint(['loan_id'], ['loan_application.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document_need',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('borrower_id', sa.Integer(), nullable=True),
    sa.Column('loan_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['borrower_id'], ['borrower_profile.id'], name='fk_need_borrower'),
    sa.ForeignKeyConstraint(['loan_id'], ['loan_application.id'], name='fk_need_loan'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('followup_task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('borrower_id', sa.Integer(), nullable=True),
    sa.Column('loan_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('assigned_to', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['borrower_id'], ['borrower_profile.id'], ),
    sa.ForeignKeyConstraint(['loan_id'], ['loan_application.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('loan_scenario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('loan_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=120), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('rate', sa.Float(), nullable=True),
    sa.Column('term_months', sa.Integer(), nullable=True),
    sa.Column('loan_type', sa.String(length=50), nullable=True),
    sa.Column('down_payment', sa.Float(), nullable=True),
    sa.Column('closing_costs', sa.Float(), nullable=True),
    sa.Column('monthly_payment', sa.Float(), nullable=True),
    sa.Column('dti', sa.Float(), nullable=True),
    sa.Column('ltv', sa.Float(), nullable=True),
    sa.Column('apr', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['loan_id'], ['loan_application.id'], name='fk_scenario_loan'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('loan_status_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('loan_id', sa.Integer(), nullable=True),
    sa.Column('event_name', sa.String(length=120), nullable=True),
    sa.Column('description', sa.String(length=400), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['loan_id'], ['loan_application.id'], name='fk_status_loan'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payment_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('borrower_profile_id', sa.Integer(), nullable=True),
    sa.Column('loan_id', sa.Integer(), nullable=True),
    sa.Column('payment_type', sa.String(length=100), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('stripe_payment_intent', sa.String(length=255), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['borrower_profile_id'], ['borrower_profile.id'], name='fk_payment_borrower'),
    sa.ForeignKeyConstraint(['loan_id'], ['loan_application.id'], name='fk_payment_loan'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('esigned_document',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('borrower_profile_id', sa.Integer(), nullable=False),
    sa.Column('loan_id', sa.Integer(), nullable=False),
    sa.Column('loan_document_id', sa.Integer(), nullable=True),
    sa.Column('document_name', sa.String(length=255), nullable=False),
    sa.Column('document_type', sa.String(length=100), nullable=True),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('envelope_id', sa.String(length=255), nullable=True),
    sa.Column('signer_email', sa.String(length=255), nullable=True),
    sa.Column('signer_name', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('status_message', sa.String(length=500), nullable=True),
    sa.Column('viewed_at', sa.DateTime(), nullable=True),
    sa.Column('signed_at', sa.DateTime(), nullable=True),
    sa.Column('pdf_original_path', sa.String(length=500), nullable=True),
    sa.Column('pdf_signed_path', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('webhook_log', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['borrower_profile_id'], ['borrower_profile.id'], ),
    sa.ForeignKeyConstraint(['loan_document_id'], ['loan_document.id'], ),
    sa.ForeignKeyConstraint(['loan_id'], ['loan_application.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('loan_application', schema=None) as batch_op:
        batch_op.add_column(sa.Column('monthly_housing_payment', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('front_end_dti', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('back_end_dti', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('monthly_debt_total', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('progress_percent', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('milestone_stage', sa.String(length=50), nullable=True))

    with op.batch_alter_table('loan_notification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('borrower_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('channel', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('title', sa.String(length=255), nullable=True))
        batch_op.alter_column('message',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=800),
               existing_nullable=True)
        batch_op.create_foreign_key(None, 'borrower_profile', ['borrower_id'], ['id'])

    with op.batch_alter_table('loan_officer_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nmls', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('signature_image', sa.String(length=255), nullable=True))

    with op.batch_alter_table('underwriter_task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('loan_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'loan_application', ['loan_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('underwriter_task', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('loan_id')

    with op.batch_alter_table('loan_officer_profile', schema=None) as batch_op:
        batch_op.drop_column('signature_image')
        batch_op.drop_column('nmls')

    with op.batch_alter_table('loan_notification', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('message',
               existing_type=sa.String(length=800),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.drop_column('title')
        batch_op.drop_column('channel')
        batch_op.drop_column('borrower_id')

    with op.batch_alter_table('loan_application', schema=None) as batch_op:
        batch_op.drop_column('milestone_stage')
        batch_op.drop_column('progress_percent')
        batch_op.drop_column('monthly_debt_total')
        batch_op.drop_column('back_end_dti')
        batch_op.drop_column('front_end_dti')
        batch_op.drop_column('monthly_housing_payment')

    op.drop_table('esigned_document')
    op.drop_table('payment_record')
    op.drop_table('loan_status_event')
    op.drop_table('loan_scenario')
    op.drop_table('followup_task')
    op.drop_table('document_need')
    op.drop_table('document_event')
    op.drop_table('communication_log')
    op.drop_table('soft_credit_report')
    op.drop_table('borrower_message')
    op.drop_table('borrower_last_contact')
    # ### end Alembic commands ###
