"""auto update

Revision ID: 242e9f35df38
Revises: fe6f8308fbfc
Create Date: 2025-11-13 05:46:23.769610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '242e9f35df38'
down_revision = 'fe6f8308fbfc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_audit_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('borrower_profile_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint(batch_op.f('ai_audit_log_borrower_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'borrower_profile', ['borrower_profile_id'], ['id'])
        batch_op.drop_column('borrower_id')

    with op.batch_alter_table('ai_intake_summary', schema=None) as batch_op:
        batch_op.add_column(sa.Column('borrower_profile_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(batch_op.f('ai_intake_summary_borrower_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'borrower_profile', ['borrower_profile_id'], ['id'])
        batch_op.drop_column('borrower_id')

    with op.batch_alter_table('loan_ai_conversation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('borrower_profile_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint(batch_op.f('loan_ai_conversation_borrower_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'borrower_profile', ['borrower_profile_id'], ['id'])
        batch_op.drop_column('borrower_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loan_ai_conversation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('borrower_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('loan_ai_conversation_borrower_id_fkey'), 'borrower_profile', ['borrower_id'], ['id'])
        batch_op.drop_column('borrower_profile_id')

    with op.batch_alter_table('ai_intake_summary', schema=None) as batch_op:
        batch_op.add_column(sa.Column('borrower_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('ai_intake_summary_borrower_id_fkey'), 'borrower_profile', ['borrower_id'], ['id'])
        batch_op.drop_column('borrower_profile_id')

    with op.batch_alter_table('ai_audit_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('borrower_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('ai_audit_log_borrower_id_fkey'), 'borrower_profile', ['borrower_id'], ['id'])
        batch_op.drop_column('borrower_profile_id')

    # ### end Alembic commands ###
