"""Recreate clean LoanAIConversation model

Revision ID: 244042f38df6
Revises: 265e3611df8e
Create Date: 2025-11-07 23:19:08.286485

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '244042f38df6'
down_revision = '265e3611df8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ai_audit_log')
    with op.batch_alter_table('loan_ai_conversation', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('loan_ai_conversation_borrower_id_fkey'), type_='foreignkey')
        batch_op.drop_column('user_message')
        batch_op.drop_column('created_at')
        batch_op.drop_column('user_role')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('borrower_id')
        batch_op.drop_column('topic')
        batch_op.drop_column('ai_response')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loan_ai_conversation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ai_response', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('topic', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('borrower_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('user_role', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('user_message', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key(batch_op.f('loan_ai_conversation_borrower_id_fkey'), 'borrower_profile', ['borrower_id'], ['id'])

    op.create_table('ai_audit_log',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('actor_role', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('action', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('result', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('ai_audit_log_pkey'))
    )
    # ### end Alembic commands ###
