"""auto update

Revision ID: 276c189025f3
Revises: 68798e46bc20
Create Date: 2026-01-28 13:03:21.106907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '276c189025f3'
down_revision = '68798e46bc20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_assistant_interactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('loan_officer_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('loan_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'loan_officer_profile', ['loan_officer_id'], ['id'])
        batch_op.create_foreign_key(None, 'loan_application', ['loan_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_assistant_interactions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('loan_id')
        batch_op.drop_column('loan_officer_id')

    # ### end Alembic commands ###
