"""auto update

Revision ID: 2cce2a050ea7
Revises: 9e1f751164d7
Create Date: 2025-11-20 19:18:14.997923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cce2a050ea7'
down_revision = '9e1f751164d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('borrower_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'borrower_profile', ['borrower_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('borrower_id')

    # ### end Alembic commands ###
