"""Add property_value and fields to PropertyAnalysis

Revision ID: 40ea79ae5eec
Revises: 6c0ee7eb1360
Create Date: 2025-11-08 01:21:59.678570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40ea79ae5eec'
down_revision = '6c0ee7eb1360'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property_analysis', schema=None) as batch_op:
        batch_op.add_column(sa.Column('property_value', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('property_type', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('address', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('ltv', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('cap_rate', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('noi', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property_analysis', schema=None) as batch_op:
        batch_op.drop_column('noi')
        batch_op.drop_column('cap_rate')
        batch_op.drop_column('ltv')
        batch_op.drop_column('address')
        batch_op.drop_column('property_type')
        batch_op.drop_column('property_value')

    # ### end Alembic commands ###
