"""Add condition_type and description to ConditionRequest

Revision ID: 490ce812a901
Revises: c2161ec27b80
Create Date: 2025-11-08 00:49:21.046494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '490ce812a901'
down_revision = 'c2161ec27b80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('condition_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('condition_type', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))

    with op.batch_alter_table('loan_officer_ai_summary', schema=None) as batch_op:
        batch_op.add_column(sa.Column('officer_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('confidence_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.drop_constraint(batch_op.f('loan_officer_ai_summary_loan_officer_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'loan_officer_profile', ['officer_id'], ['id'])
        batch_op.drop_column('loan_officer_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loan_officer_ai_summary', schema=None) as batch_op:
        batch_op.add_column(sa.Column('loan_officer_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('loan_officer_ai_summary_loan_officer_id_fkey'), 'loan_officer_profile', ['loan_officer_id'], ['id'])
        batch_op.drop_column('updated_at')
        batch_op.drop_column('confidence_score')
        batch_op.drop_column('officer_id')

    with op.batch_alter_table('condition_request', schema=None) as batch_op:
        batch_op.drop_column('description')
        batch_op.drop_column('condition_type')

    # ### end Alembic commands ###
