"""auto update

Revision ID: 4b111ce5e0f9
Revises: ab0e053a2682
Create Date: 2025-11-12 17:51:53.394030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b111ce5e0f9'
down_revision = 'ab0e053a2682'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('system_generated', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_column('system_generated')

    # ### end Alembic commands ###
