"""Add decision fields to LoanApplication

Revision ID: 4b87736ccfcf
Revises: 606e5a61ab49
Create Date: 2025-11-10 13:34:00.334996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b87736ccfcf'
down_revision = '606e5a61ab49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loan_application', schema=None) as batch_op:
        batch_op.add_column(sa.Column('decision_notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('decision_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loan_application', schema=None) as batch_op:
        batch_op.drop_column('decision_date')
        batch_op.drop_column('decision_notes')

    # ### end Alembic commands ###
