"""Add is_active to LoanApplication

Revision ID: 4be4b1ce7d37
Revises: fb2c84780c28
Create Date: 2026-02-25 00:41:18.511167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4be4b1ce7d37'
down_revision = 'fb2c84780c28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loan_application', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loan_application', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
