"""Add risk_level and ltv_ratio to LoanApplication

Revision ID: 606e5a61ab49
Revises: 79f6bd10eca0
Create Date: 2025-11-10 13:27:48.784945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '606e5a61ab49'
down_revision = '79f6bd10eca0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loan_application', schema=None) as batch_op:
        batch_op.add_column(sa.Column('risk_level', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('ltv_ratio', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loan_application', schema=None) as batch_op:
        batch_op.drop_column('ltv_ratio')
        batch_op.drop_column('risk_level')

    # ### end Alembic commands ###
