"""Add LoanNotification, FollowUpItem, MessageThread, ContractorPayments, DocumentRequest, UnderwriterAuditLog, UnderwriterTask

Revision ID: 61567f0fb246
Revises: 0c35f7e30e0e
Create Date: 2025-11-10 07:35:53.842513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61567f0fb246'
down_revision = '0c35f7e30e0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('follow_up_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('borrower_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_done', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['borrower_id'], ['borrower_profile.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('follow_up_item')
    # ### end Alembic commands ###
