"""Add review_status, sent_to_underwriter, reviewed_at, notes, document_name to LoanDocument

Revision ID: 67e96cf8eb5e
Revises: 1c9076aae2bb
Create Date: 2025-11-08 11:48:34.003878

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67e96cf8eb5e'
down_revision = '1c9076aae2bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loan_document', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('document_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('submitted_file', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('submitted_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loan_document', schema=None) as batch_op:
        batch_op.drop_column('submitted_at')
        batch_op.drop_column('submitted_file')
        batch_op.drop_column('document_name')
        batch_op.drop_column('notes')

    # ### end Alembic commands ###
