"""auto update

Revision ID: 68798e46bc20
Revises: 48195487a08b
Create Date: 2025-11-21 14:22:42.894205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68798e46bc20'
down_revision = '48195487a08b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saved_properties', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sqft', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saved_properties', schema=None) as batch_op:
        batch_op.drop_column('sqft')

    # ### end Alembic commands ###
