"""Add property_name to PropertyAnalysis

Revision ID: 6c0ee7eb1360
Revises: 490ce812a901
Create Date: 2025-11-08 01:13:59.692510

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c0ee7eb1360'
down_revision = '490ce812a901'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property_analysis', schema=None) as batch_op:
        batch_op.add_column(sa.Column('property_name', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property_analysis', schema=None) as batch_op:
        batch_op.drop_column('property_name')

    # ### end Alembic commands ###
