"""Add zipcode to SavedProperty

Revision ID: 791bff9eae44
Revises: f3143b696823
Create Date: 2026-02-16 11:22:06.726736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '791bff9eae44'
down_revision = 'f3143b696823'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saved_properties', schema=None) as batch_op:
        batch_op.add_column(sa.Column('zipcode', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saved_properties', schema=None) as batch_op:
        batch_op.drop_column('created_at')
        batch_op.drop_column('zipcode')

    # ### end Alembic commands ###
