"""auto update

Revision ID: 7eb6e9dd2c83
Revises: c7881804304d
Create Date: 2025-11-20 22:11:29.494592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7eb6e9dd2c83'
down_revision = 'c7881804304d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credit_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('report_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credit_profile', schema=None) as batch_op:
        batch_op.drop_column('report_date')

    # ### end Alembic commands ###
