"""add deal_shares table

Revision ID: 8e94743363e4
Revises: aedf39af534a
Create Date: 2026-02-24 18:18:23.327511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e94743363e4'
down_revision = 'aedf39af534a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deal_shares',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('borrower_user_id', sa.Integer(), nullable=False),
    sa.Column('loan_officer_user_id', sa.Integer(), nullable=True),
    sa.Column('property_id', sa.String(length=120), nullable=True),
    sa.Column('strategy', sa.String(length=32), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('results_json', sa.JSON(), nullable=True),
    sa.Column('comps_json', sa.JSON(), nullable=True),
    sa.Column('resolved_json', sa.JSON(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('opened_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('deal_shares', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_deal_shares_borrower_user_id'), ['borrower_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_deal_shares_loan_officer_user_id'), ['loan_officer_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_deal_shares_property_id'), ['property_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deal_shares', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_deal_shares_property_id'))
        batch_op.drop_index(batch_op.f('ix_deal_shares_loan_officer_user_id'))
        batch_op.drop_index(batch_op.f('ix_deal_shares_borrower_user_id'))

    op.drop_table('deal_shares')
    # ### end Alembic commands ###
