"""Rename project_budget to project_budgets

Revision ID: 8eff6132820f
Revises: 0b9881ace246
Create Date: 2025-11-09 12:12:00.155821

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8eff6132820f'
down_revision = '0b9881ace246'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_budgets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('borrower_profile_id', sa.Integer(), nullable=False),
    sa.Column('loan_app_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('project_name', sa.String(length=120), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_budget', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('total_cost', sa.Float(), nullable=True),
    sa.Column('materials_cost', sa.Float(), nullable=True),
    sa.Column('labor_cost', sa.Float(), nullable=True),
    sa.Column('contingency', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['borrower_profile_id'], ['borrower_profile.id'], ),
    sa.ForeignKeyConstraint(['loan_app_id'], ['loan_application.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('budget_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['budget_id'], ['project_budgets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('project_budget')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_budget',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('borrower_profile_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('loan_app_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_cost', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('materials_cost', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('labor_cost', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('contingency', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('total_amount', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('project_name', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('total_budget', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['borrower_profile_id'], ['borrower_profile.id'], name=op.f('project_budget_borrower_profile_id_fkey')),
    sa.ForeignKeyConstraint(['loan_app_id'], ['loan_application.id'], name=op.f('project_budget_loan_app_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('project_budget_pkey'))
    )
    op.drop_table('project_expenses')
    op.drop_table('project_budgets')
    # ### end Alembic commands ###
