"""auto update

Revision ID: 9e1f751164d7
Revises: 1ea77ca3457d
Create Date: 2025-11-20 19:04:17.484260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e1f751164d7'
down_revision = '1ea77ca3457d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loan_application', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loan_application', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###
