"""auto update

Revision ID: a49f234b0769
Revises: 242e9f35df38
Create Date: 2025-11-13 17:13:50.464180

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a49f234b0769'
down_revision = '242e9f35df38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_resolved', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document_requests', schema=None) as batch_op:
        batch_op.drop_column('is_resolved')

    # ### end Alembic commands ###
