"""Add review_status and sent_to_underwriter to LoanDocument

Revision ID: a79c4ab95040
Revises: 67e96cf8eb5e
Create Date: 2025-11-08 11:53:54.150004

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a79c4ab95040'
down_revision = '67e96cf8eb5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loan_document', schema=None) as batch_op:
        batch_op.add_column(sa.Column('review_status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('sent_to_underwriter', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('reviewed_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.drop_column('uploaded_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loan_document', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uploaded_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.drop_column('updated_at')
        batch_op.drop_column('reviewed_at')
        batch_op.drop_column('sent_to_underwriter')
        batch_op.drop_column('review_status')

    # ### end Alembic commands ###
