"""auto update

Revision ID: ae7bad3a6da2
Revises: ee2ea8e9cd3b
Create Date: 2025-11-09 18:07:39.180675

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ae7bad3a6da2'
down_revision = 'ee2ea8e9cd3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_path', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('verified_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('loan_document', schema=None) as batch_op:
        batch_op.drop_column('requested_by')
        batch_op.drop_column('verified_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loan_document', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verified_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('requested_by', sa.VARCHAR(length=120), autoincrement=False, nullable=True))

    with op.batch_alter_table('document_requests', schema=None) as batch_op:
        batch_op.drop_column('verified_at')
        batch_op.drop_column('file_path')

    # ### end Alembic commands ###
