"""add deals table

Revision ID: aedf39af534a
Revises: fa4187c42e98
Create Date: 2026-02-24 17:46:33.490491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aedf39af534a'
down_revision = 'fa4187c42e98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.String(length=120), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('strategy', sa.String(length=32), nullable=True),
    sa.Column('inputs_json', sa.JSON(), nullable=True),
    sa.Column('results_json', sa.JSON(), nullable=True),
    sa.Column('comps_json', sa.JSON(), nullable=True),
    sa.Column('resolved_json', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('deals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_deals_property_id'), ['property_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_deals_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_deals_user_id'))
        batch_op.drop_index(batch_op.f('ix_deals_property_id'))

    op.drop_table('deals')
    # ### end Alembic commands ###
