"""Add sentiment to CallLog

Revision ID: c1d19bb33b8d
Revises: d538f98d9edd
Create Date: 2025-11-11 07:24:35.227406

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1d19bb33b8d'
down_revision = 'd538f98d9edd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('call_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sentiment', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('call_log', schema=None) as batch_op:
        batch_op.drop_column('sentiment')

    # ### end Alembic commands ###
