"""auto update

Revision ID: c2161ec27b80
Revises: 244042f38df6
Create Date: 2025-11-07 23:52:12.879333

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c2161ec27b80'
down_revision = '244042f38df6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('module', sa.String(length=100), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('loan_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['loan_id'], ['loan_application.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('call_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('contact_name', sa.String(length=120), nullable=True),
    sa.Column('contact_phone', sa.String(length=20), nullable=True),
    sa.Column('related_lead_id', sa.Integer(), nullable=True),
    sa.Column('related_loan_id', sa.Integer(), nullable=True),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('outcome', sa.String(length=120), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('recording_url', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['related_lead_id'], ['lead.id'], ),
    sa.ForeignKeyConstraint(['related_loan_id'], ['loan_application.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('loan_ai_conversation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('borrower_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('user_role', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('topic', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('user_message', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('ai_response', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key(None, 'borrower_profile', ['borrower_id'], ['id'])
        batch_op.drop_column('timestamp')
        batch_op.drop_column('sender')
        batch_op.drop_column('message')

    with op.batch_alter_table('loan_officer_ai_summary', schema=None) as batch_op:
        batch_op.add_column(sa.Column('summary_text', sa.Text(), nullable=True))
        batch_op.drop_column('insights')
        batch_op.drop_column('behavioral_index')
        batch_op.drop_column('summary')
        batch_op.drop_column('communication_score')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loan_officer_ai_summary', schema=None) as batch_op:
        batch_op.add_column(sa.Column('communication_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('summary', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('behavioral_index', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('insights', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_column('summary_text')

    with op.batch_alter_table('loan_ai_conversation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('sender', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('ai_response')
        batch_op.drop_column('user_message')
        batch_op.drop_column('topic')
        batch_op.drop_column('user_role')
        batch_op.drop_column('borrower_id')

    op.drop_table('call_log')
    op.drop_table('ai_audit_log')
    # ### end Alembic commands ###
