"""auto update

Revision ID: c7881804304d
Revises: 4cf3bb609ab6
Create Date: 2025-11-20 22:10:25.326961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7881804304d'
down_revision = '4cf3bb609ab6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credit_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('score', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credit_profile', schema=None) as batch_op:
        batch_op.drop_column('score')

    # ### end Alembic commands ###
