"""Add last_deal column to Partner model

Revision ID: d538f98d9edd
Revises: d6183419ef9b
Create Date: 2025-11-10 18:26:08.680529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd538f98d9edd'
down_revision = 'd6183419ef9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('partners', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_deal', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('partners', schema=None) as batch_op:
        batch_op.drop_column('last_deal')

    # ### end Alembic commands ###
