"""Add review fields to LoanDocument

Revision ID: d6183419ef9b
Revises: 4b87736ccfcf
Create Date: 2025-11-10 13:38:56.227304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6183419ef9b'
down_revision = '4b87736ccfcf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loan_document', schema=None) as batch_op:
        batch_op.add_column(sa.Column('review_notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('reviewed_by', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loan_document', schema=None) as batch_op:
        batch_op.drop_column('reviewed_by')
        batch_op.drop_column('review_notes')

    # ### end Alembic commands ###
