"""Add file_path + verified_at to DocumentRequest and timestamps to ConditionRequest

Revision ID: ee2ea8e9cd3b
Revises: d20234482fe4
Create Date: 2025-11-09 17:23:08.515710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee2ea8e9cd3b'
down_revision = 'd20234482fe4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('condition_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('loan_document', schema=None) as batch_op:
        batch_op.add_column(sa.Column('requested_by', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('verified_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loan_document', schema=None) as batch_op:
        batch_op.drop_column('verified_at')
        batch_op.drop_column('requested_by')

    with op.batch_alter_table('condition_request', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###
