"""auto update

Revision ID: f3143b696823
Revises: 276c189025f3
Create Date: 2026-02-05 13:31:23.631156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3143b696823'
down_revision = '276c189025f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('underwriting_condition', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('underwriting_condition', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###
