"""auto update

Revision ID: f49257f200ea
Revises: 7eb6e9dd2c83
Create Date: 2025-11-20 22:13:00.657067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f49257f200ea'
down_revision = '7eb6e9dd2c83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credit_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('public_records', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('total_debt', sa.Numeric(precision=12, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credit_profile', schema=None) as batch_op:
        batch_op.drop_column('total_debt')
        batch_op.drop_column('public_records')

    # ### end Alembic commands ###
