"""add lo_is_external columns

Revision ID: f80fae86417f
Revises: f18b98c11cad
Create Date: 2026-04-19 14:32:28.389436

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f80fae86417f'
down_revision = 'f18b98c11cad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vip_assistant_actions', schema=None) as batch_op:
        batch_op.drop_column('miles')
        batch_op.drop_column('amount')
        batch_op.drop_column('notes')

    with op.batch_alter_table('vip_assistant_suggestions', schema=None) as batch_op:
        batch_op.drop_column('proposed_miles')
        batch_op.drop_column('due_at')
    with op.batch_alter_table('vip_design_annotations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('vip_design_projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contact_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=False))
        batch_op.create_foreign_key(None, 'vip_contacts', ['contact_id'], ['id'])

    with op.batch_alter_table('vip_expenses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('market', sa.String(length=100), nullable=True))

    with op.batch_alter_table('vip_income', schema=None) as batch_op:
        batch_op.add_column(sa.Column('market', sa.String(length=100), nullable=True))

    with op.batch_alter_table('vip_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lo_is_external', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('lo_licensed_residential', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('lo_company_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('lo_license_number', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('lo_license_state', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('lo_nmls', sa.String(length=50), nullable=True))
        batch_op.create_foreign_key(None, 'companies', ['lo_company_id'], ['id'])

    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vip_profiles', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('lo_nmls')
        batch_op.drop_column('lo_license_state')
        batch_op.drop_column('lo_license_number')
        batch_op.drop_column('lo_company_id')
        batch_op.drop_column('lo_licensed_residential')
        batch_op.drop_column('lo_is_external')

    with op.batch_alter_table('vip_income', schema=None) as batch_op:
        batch_op.drop_column('market')

    with op.batch_alter_table('vip_expenses', schema=None) as batch_op:
        batch_op.drop_column('market')

    with op.batch_alter_table('vip_design_projects', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('status')
        batch_op.drop_column('contact_id')

    with op.batch_alter_table('vip_design_annotations', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('vip_assistant_suggestions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('due_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('proposed_miles', sa.INTEGER(), autoincrement=False, nullable=True))

    with op.batch_alter_table('vip_assistant_actions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('amount', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('miles', sa.INTEGER(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###