"""auto update

Revision ID: fa4187c42e98
Revises: 791bff9eae44
Create Date: 2026-02-23 18:15:30.041364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa4187c42e98'
down_revision = '791bff9eae44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saved_properties', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resolved_json', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('resolved_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saved_properties', schema=None) as batch_op:
        batch_op.drop_column('resolved_at')
        batch_op.drop_column('resolved_json')

    # ### end Alembic commands ###
