"""auto update

Revision ID: fe6f8308fbfc
Revises: 4b111ce5e0f9
Create Date: 2025-11-13 05:44:19.161475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe6f8308fbfc'
down_revision = '4b111ce5e0f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('follow_up_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('borrower_profile_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(batch_op.f('follow_up_item_borrower_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'borrower_profile', ['borrower_profile_id'], ['id'])
        batch_op.drop_column('borrower_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('follow_up_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('borrower_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('follow_up_item_borrower_id_fkey'), 'borrower_profile', ['borrower_id'], ['id'])
        batch_op.drop_column('borrower_profile_id')

    # ### end Alembic commands ###
