"""Models for engine training data collection and job tracking."""

from datetime import datetime
from LoanMVP.extensions import db


class StudioGenerationLog(db.Model):
    """One row per image generated by Build Studio, Design Studio, or Project Build."""
    __tablename__ = "studio_generation_logs"

    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey("user.id"), nullable=True, index=True)
    feature = db.Column(db.String(50), nullable=False)       # build_studio | design_studio | project_build
    provider = db.Column(db.String(30), nullable=False)      # engine | dalle3
    output_mode = db.Column(db.String(50), nullable=True)    # blueprint | exterior_front | interior | ...
    prompt = db.Column(db.Text, nullable=True)               # prompt sent to provider
    payload_json = db.Column(db.Text, nullable=True)         # full request payload (JSON)
    image_url = db.Column(db.String(512), nullable=True)     # public CDN URL of saved image
    quality_rating = db.Column(db.Integer, nullable=True)    # 1-5 user rating
    approved_for_training = db.Column(db.Boolean, default=False, nullable=False)
    created_at = db.Column(db.DateTime, default=datetime.utcnow, nullable=False)

    def __repr__(self):
        return f"<StudioGenerationLog id={self.id} feature={self.feature} provider={self.provider}>"


class AcademyChatLog(db.Model):
    """One row per Academy chat exchange (user message + AI response)."""
    __tablename__ = "academy_chat_logs"

    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey("user.id"), nullable=True, index=True)
    session_key = db.Column(db.String(100), nullable=True)   # anonymous session fingerprint
    tier = db.Column(db.String(30), nullable=True)           # starter | pro | elite | lending
    feature = db.Column(db.String(30), nullable=False, default="chat")  # chat | business_plan
    system_prompt = db.Column(db.Text, nullable=True)
    messages_json = db.Column(db.Text, nullable=True)        # full messages array (JSON)
    ai_response = db.Column(db.Text, nullable=True)          # assistant reply text
    model = db.Column(db.String(60), nullable=True)
    thumbs_up = db.Column(db.Boolean, nullable=True)         # None=unrated, True=good, False=bad
    approved_for_training = db.Column(db.Boolean, default=False, nullable=False)
    created_at = db.Column(db.DateTime, default=datetime.utcnow, nullable=False)

    def __repr__(self):
        return f"<AcademyChatLog id={self.id} feature={self.feature} tier={self.tier}>"


class TrainingJob(db.Model):
    """Tracks Replicate (or other provider) fine-tuning jobs."""
    __tablename__ = "training_jobs"

    id = db.Column(db.Integer, primary_key=True)
    job_type = db.Column(db.String(50), nullable=False)      # sdxl_lora | academy_finetune
    provider = db.Column(db.String(30), default="replicate")
    external_job_id = db.Column(db.String(255), nullable=True)
    status = db.Column(db.String(30), default="pending")     # pending | running | succeeded | failed | canceled
    config_json = db.Column(db.Text, nullable=True)          # training config sent to provider
    result_json = db.Column(db.Text, nullable=True)          # response from provider
    model_url = db.Column(db.String(512), nullable=True)     # output model/weights URL
    sample_count = db.Column(db.Integer, nullable=True)      # number of training samples used
    triggered_by = db.Column(db.Integer, db.ForeignKey("user.id"), nullable=True)
    created_at = db.Column(db.DateTime, default=datetime.utcnow, nullable=False)
    completed_at = db.Column(db.DateTime, nullable=True)

    def __repr__(self):
        return f"<TrainingJob id={self.id} type={self.job_type} status={self.status}>"


class UserCourseUnlock(db.Model):
    """Tracks which courses a user has enrolled in beyond their subscription-included course."""
    # Table and column names keep the old 'avenue' names so no DB migration is needed.
    __tablename__ = "user_avenue_unlocks"

    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey("user.id"), nullable=False, index=True)
    course_id = db.Column('avenue_id', db.String(50), nullable=False)
    stripe_payment_id = db.Column(db.String(255), nullable=True)
    unlocked_at = db.Column(db.DateTime, default=datetime.utcnow, nullable=False)

    __table_args__ = (
        db.UniqueConstraint('user_id', 'avenue_id', name='uq_user_avenue'),
    )

    def __repr__(self):
        return f"<UserCourseUnlock user={self.user_id} course={self.course_id}>"


class AcademyLessonScore(db.Model):
    """Tracks quiz scores for individual lessons."""
    __tablename__ = "academy_lesson_scores"

    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey("user.id"), nullable=False, index=True)
    module_id = db.Column(db.String(50), nullable=False)
    lesson_index = db.Column(db.Integer, nullable=False)
    score = db.Column(db.Integer, nullable=False)              # 0-100 percentage
    attempts = db.Column(db.Integer, default=1, nullable=False)
    passed = db.Column(db.Boolean, default=False, nullable=False)
    completed_at = db.Column(db.DateTime, default=datetime.utcnow, nullable=False)

    __table_args__ = (
        db.UniqueConstraint('user_id', 'module_id', 'lesson_index', name='uq_user_lesson_score'),
    )

    def __repr__(self):
        return f"<AcademyLessonScore user={self.user_id} module={self.module_id} lesson={self.lesson_index} score={self.score}>"


class AcademyLessonProgress(db.Model):
    """Tracks which lessons a user has completed in Ravlo Academy."""
    __tablename__ = "academy_lesson_progress"

    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey("user.id"), nullable=False, index=True)
    module_id = db.Column(db.String(50), nullable=False)
    lesson_index = db.Column(db.Integer, nullable=False)
    completed_at = db.Column(db.DateTime, default=datetime.utcnow, nullable=False)

    __table_args__ = (
        db.UniqueConstraint('user_id', 'module_id', 'lesson_index', name='uq_user_module_lesson'),
    )

    def __repr__(self):
        return f"<AcademyLessonProgress user={self.user_id} module={self.module_id} lesson={self.lesson_index}>"
